[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.0.4"
  export = ["sfdc_new_account_to_netsuite_customer"]
  icon = "docs/icon.png"
  keywords = ["Type/Webhook","Category/Integration"]
  name = "sfdc_new_account_to_netsuite_customer"
  org = "yashodperera"
  version = "1.0.1"

